config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rides, only: [ :index, :show]

  resources :rides do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get 'autocomplete-station', to: 'start_points#autocomplete_stations'
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id               :integer          not null, primary key
#  ride_id          :integer
#  user_id          :integer
#  passenger_number :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Booking < ApplicationRecord
  belongs_to :ride
  belongs_to :user

  validates :passenger_number, presence: true, inclusion: { in: (0..10),
    message: "Must be a number between 0 and 10"}

  # enables to call end_point on @booking and returns @booking.ride.end_point
  delegate :end_point, :start_point, to: :ride
  enum state: [:pending , :paid ]
  monetize :amount_cents


def calculate_amount
  self.ride.price * self.passenger_number

end

  # other possibility to avoid doing a belongs_to:end_point through :ride is :
  # def end_point
  #   ride.end_point
  # end

  # def start_point
  #   ride.start_point
  # end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @ride = Ride.find(params[:ride_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.ride = @ride
    @booking.pending!

    if @booking.save
      redirect_to booking_path(@booking.id)
    else
      render 'rides/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])


  end

  private

  def booking_params
    params.require(:booking).permit(:passenger_number)
  end

end

app/views/bookings/show.html.erb
<div class="container container-content">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10">

        <% if @booking.state == "paid" %>
        <h3 class="mb mt text-center">Réservation confirmée!</h3>
        <%else%>
        <h3 class="mb mt text-center">Récapitulatif de la réservation</h3>
        <%end%>
        <div class="traject-confirmation">
          <p><strong class=" text-left color-totor-dark  ">Départ :</strong> <%= @booking.start_point.station %></p>

          <p><strong class=" text-left color-totor-dark ">Arrivée :</strong> <%= @booking.end_point.address %></p>
          <p><strong class=" text-left color-totor-dark ">Conducteur :</strong> <%= @booking.ride.user.first_name %> </p>
          <p><strong class=" text-left color-totor-dark ">Arrivée de son train :</strong> <%= @booking.ride.train_arrival_at.strftime(" %d %b %Y") %> à <%= @booking.ride.train_arrival_at.strftime("%Hh%M")  %></p>
          <p><strong class=" text-left color-totor-dark ">Places réservées :</strong> <%= @booking.passenger_number %></p>
        </div>

    </div>
  </div>
<% if @booking.state == "paid" %>
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10">
      <div class="text-left traject-confirmation mt">
        <p>"<%= @booking.ride.description %>"</p>
        <p>Pour plus d'infos, appelez<strong> <%= @booking.ride.user.first_name %></strong> au <%= @booking.ride.user.phone_number %></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-offset-2 col-xs-10 col-sm-offset-4 col-sm-10 mt+ mb">
      <div class="car-with-passengers text-center">
        <div class="car-passenger">

          <%= cl_image_tag choose_photo_path(current_user), height: 40, width: 40, class:'image-circle'  %>

        </div>
        <div class="car-driver">
          <%= cl_image_tag choose_photo_path(@booking.ride.user), height: 40, width: 40, class:'image-circle'  %>
        </div>
        <div class="car">
          <%= image_tag 'car.svg', height: 200, width: 200 %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">

    <div class="text-center col-xs-10 col-xs-offset-1">
      <h3> A très bientôt sur </h3>
      <%= image_tag "logo.png", height: 50, class: "img-responsive" %>
    </div>
  </div>
<% end %>

<% if @booking.state == "pending" %>

<%= form_tag booking_payments_path(@booking) do %>
  <article class="text-center mt+ ml-- ">
    <label class="amount">
      <span> Total : <%= humanized_money_with_symbol(@booking.calculate_amount) %></span>
    </label>
  </article>

 <div class="text-center mt-- ml--">
    <%= form_tag bookings_path do %>
      <%= hidden_field_tag 'booking_id', @booking.id %>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button " style="min-width: 100px;"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-name="Mon trajet"
        data-email=" pour <%= current_user.email %>"
        data-description="Réservation <%= @booking.id %>"
        data-amount="<%= @booking.amount_cents %>"
        data-label="Payer"
        data-locale=auto
        data-currency="<%= @booking.amount.currency %>"></script>

    <% end %>
  </div>
<% end %>
<% end %>
  </div>
</div>