config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rides, only: [ :index, :show]

  resources :rides do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get 'autocomplete-station', to: 'start_points#autocomplete_stations'
end

app/models/ride.rb
# == Schema Information
#
# Table name: rides
#
#  id                 :integer          not null, primary key
#  train_ref          :string
#  train_arrival_date :date
#  user_id            :integer
#  passengers_allowed :integer
#  start_point_id     :integer
#  end_point_id       :integer
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  train_arrival_time :time
#  car_brand          :string
#  car_model          :string
#

class Ride < ApplicationRecord
  belongs_to :user
  belongs_to :start_point
  belongs_to :end_point
  has_many :bookings

  validates :train_ref, presence: true
  validates :train_arrival_at, presence: true
  validates :passengers_allowed, presence: true, inclusion: { in: (0..10), message: "Entrer un entier entre 0 et 10"}
  validates :description, presence: true
  validates :price, presence: true
  monetize :price_cents
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  before_action :set_ride, only: :show
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    # @rides = Ride.all
    @search_params = params[:search]

    passenger_number = @search_params[:passenger_number].to_i

    if @search_params[:start_point].blank?
      flash[:alert] = "Veuillez remplir le point de départ !"
      redirect_to root_path
    end

    matching_train = @search_params[:train_ref]
    filters = {
      start_points: { station: @search_params[:start_point]},
      passengers_allowed: passenger_number..10
    }

    if params[:train_arrival_at].present?

      arrival_at = params[:train_arrival_at].to_datetime
      filters[:train_arrival_at] = arrival_at..arrival_at.tomorrow.at_midnight
    end

    rides = Ride.joins(:start_point).where(filters).order(:train_arrival_at)

    @rides_same_train = rides.select do |ride|
      ride.train_ref == matching_train
    end

    @rides_not_same_train = rides - @rides_same_train

  end

        # On filtre les rides dont :
        # le start point et la gare d'arrivée matchent
        # le jour du ride match avec le jour cherché.
        # l'heure du ride est postérieur ou égale à l'heure cherché
        # le passenger allowed est superieur ou egal au passager number dans search

            # if no matching return : désolé il n'y a pas de trajet au départ
            # de votre gare

            #else
              # select les rides dont le num de train est egal au num du train
              # du formulaire
              # return ces rides en fonction par distance croissante
              # entre (destination final form et destination final ride)

  def show

    points = [@ride.start_point, @ride.end_point]

    @markers = Gmaps4rails.build_markers(points) do |point, marker|
      marker.lat point.lat
      marker.lng point.long
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    @booking = Booking.new
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_ride
    @ride = Ride.find(params[:id])
  end

  def ride_params
    params.require(:ride).permit(
      :train_ref, :train_arrival_at, :user_id, :passengers_allowed, :start_point_id, :end_point_id,
      :description, :start_date, :car_model, :car_brand
    )
  end
end

app/views/rides/_googlemap.html.erb
      <div id="map" style="width: 100%; height: 300px;">
    </div>



        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
          /* var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @markers.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
            */

        var directionsDisplay = new google.maps.DirectionsRenderer();
        var directionsService = new google.maps.DirectionsService();

        function calcRoute() {
          var origin      = new google.maps.LatLng(<%= @markers.first[:lat] %>, <%= @markers.first[:lng] %>);
          var destination = new google.maps.LatLng(<%= @markers.last[:lat] %>, <%= @markers.last[:lng] %>);
          var request = {
              origin:      origin,
              destination: destination,
              travelMode:  google.maps.TravelMode.DRIVING
          };
          directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
              directionsDisplay.setDirections(response);
            }
          });
        }

        calcRoute();

        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: {id: 'map'}}, function(){
          directionsDisplay.setMap(handler.getMap());
        });

        <% end %>
      <% end %>

app/views/rides/_ride.html.erb
<% rides.each do |r| %>
  <%= link_to ride_path(r, request.query_parameters) do %>
    <div class="col-xs-offset-1 col-xs-10 traject-card mb-">
      <div class= "card-content-sides col-xs-4">
        <div>
          <% if r.user.photo? %>
            <%= cl_image_tag r.user.photo.path, width: 50, height: 50, crop: :fill,class: 'image-circle ', "data-toggle" => "dropdown" %>
            <% else %>
            <%= image_tag 'default_avatar_pic.svg', width: 50, height: 50, crop: :fill, class: 'image-circle', "data-toggle" => "dropdown" %>
            <% end %>
        </div>
        <div>
          <p class="pl"><%= r.user.first_name %> </p>
        </div>
      </div>
      <div class= "col-xs-offset-1 col-xs-2">
          <p>         </p>
      </div>
      <div class= "card-content-sides col-xs-6">
          <p> <%= r.end_point.address.split(" ").last %> - <%= r.price_cents/100 %>€/Pers</p>
      </div>
    </div>
  <% end  %>
<% end  %>

app/views/rides/_rides.html.erb
<% rides.each do |r| %>
  <%= link_to ride_path(r, request.query_parameters) do %>
    <div class="col-xs-offset-1 col-xs-10 traject-card mb-">
      <div class= "col-xs-2 " style="padding-left: 6px;">
        <% if r.user.photo? %>
          <%= cl_image_tag r.user.photo.path, width: 50, height: 50, crop: :fill,class: 'image-circle ', "data-toggle" => "dropdown" %>
          <% else %>
          <%= image_tag 'default_avatar_pic.svg', width: 50, height: 50, crop: :fill, class: 'image-circle', "data-toggle" => "dropdown" %>
        <% end %>
      </div>
      <div class= "card-content-center col-xs-offset-1 col-xs-6   color-totor-dark">
       <p><%= r.user.first_name %> </p>
       <p> <%= r.end_point.address.split(" ").last %> </p>
      </div>
      <div class= " price-label col-xs-offset-1 col-xs-3 col-sm-offset-3 col-sm-2 col-md-offset-1 col-md-2 text-center color-totor-dark">
          <p> <%= r.price_cents/100 %>€/</p>
          <p> Pers</></p>
      </div>
    </div>
  <% end %>
<% end  %>

app/views/rides/_stepprogress.html.erb
  <ul class="StepProgress">
    <li class="StepProgress-item is-done"><%= @ride.start_point.station %></li>
    <li class="StepProgress-item is-done"><%= @ride.end_point.address %>
  </ul>

app/views/rides/index.html.erb
<div class="container">
  <div class = "row ">
    <div class= "col-xs-12 text-center">
      <div class= "mt+ mt+ mt+">
         <% if (@rides_same_train == [] && @rides_not_same_train == []) %>

          <h6> Désolé, aucun trajet n'est disponible
            <br> à ce moment de la journée
            <br> pour votre destination</h6>

          <h6> A très bientôt !</h6>


          <%= link_to "Revenir à la recherche", root_path(request.query_parameters), class: "btn btn-default col-xs-12 soft-angle  mt+ mt+ mb++ pd" %>
        </div>
      <% else %>

      <h3>Trajets disponibles</h3>

      <% end %>

    </div>
  </div>
</div>
<% if @rides_same_train.any? %>
  <div class="rides-wrapper pb pt">
    <div class="container">
      <div class="row">
        <div class="col-xs-offset-1 col-xs-10">
          <h4 class="text-color-white">Dans votre train ! </h4>
            <h5 class="text-color-white">  <%= @rides_same_train.first.train_arrival_at.strftime(" %d %b %Y") %></h5>
            <h5 class="text-color-white"><%= @rides_same_train.first.start_point.station %> <br/><strong>  arrivée   </strong>     <%= @rides_same_train.first.train_arrival_at.strftime("%Hh%M") %>
            </h5>
        </div>
      </div>

      <div class="row">
          <%= render 'rides', rides: @rides_same_train %>
      </div>
    </div>
  </div>
<% end %>

  <div class="container">
    <% @rides_not_same_train.group_by(&:train_ref).each do |train_ref, rides|%>
      <div class=" mt mb">
        <div class="row ">
          <div class="col-xs-offset-1 col-xs-10">
              <h5> <%= rides.first.train_arrival_at.strftime(" %d %b %Y")%></h5>
                <h5 ><%= rides.first.start_point.station %> <br/><strong>  arrivée   </strong>
                   <%= rides.first.train_arrival_at.strftime("%Hh%M") %>
                </h5>
          </div>
        </div>
        <div class="row">
          <%= render 'rides', rides: rides %>
        </div>
      </div>
    <% end %>
  </div>

app/views/rides/show.html.erb
<div class="container">
  <div class= "row">
    <div class="col-xs-12 pt pb ">
      <div class='ride-information-flex'>
      <div class="col-xs-3 col-sm-2 mt+">
      <% if @ride.user.photo? %>
        <%= cl_image_tag @ride.user.photo.path, width: 70, height: 70, crop: :fill,class: 'image-circle', "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag 'default_avatar_pic.svg', width: 70, height: 70, crop: :fill, class: 'image-circle', "data-toggle" => "dropdown" %>
        <% end %>
      </div>
      <div class="col-xs-9 col-sm-8">
        <div>
          <h3>Trajet de <%= @ride.user.first_name %></h4>
          <div class='ride-information'>

          <p> <strong>Arrivée</strong> : <%= @ride.start_point.station %>
          <br> <strong>Le</strong> : <%= @ride.train_arrival_at.strftime(" %d %b %Y") %> à <%= @ride.train_arrival_at.strftime(" %Hh%M")%> </p>
        </div>
        </div>
      </div>
    </div>
    </div>
    <div class= "row">
      <div class="step-progress">
      <div class="col-xs-8 pt+ pb+ ">
        <%= render 'stepprogress' %>
        </div>
      </div>



     <div class= " price-label text-center color-totor-dark col-xs-2  col-offset-sm-8 col-sm-2 mt+ mb+ pr  ">
          <p> <%= @ride.price %>€/</p>
          <p> Pers</p>
      </div>

    </div>
  </div>

  <%= render 'googlemap' %>

<div>
  <%= simple_form_for [@ride, @booking] , wrapper: :inline_form do |f| %>
    <%= f.input :passenger_number,
    collection: [
      ["1 passager", 1],
      ["2 passagers", 2],
      ["3 passagers", 3],
      ["4 passagers", 4],
      ["5 passagers", 5],
      ["6 passagers", 6],
      ["7 passagers", 7]
    ],
    selected: choose_passenger_value,
    input_html: { class: "form-control soft-angle color-totor-light-gray font-16 mt" } %>

    <%= f.button :submit, "Réserver ce trajet", class: "btn btn-default col-xs-12 soft-angle   mb pd" %>
  <% end %>
  <%= link_to "Revenir à la liste de trajets", rides_path(request.query_parameters), class: "btn btn-default col-xs-12 soft-angle  mb++ pd" %>





</div>

</div>